# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  forest_env_secret: 6d933031cedf1444da75397b5ff250d5fd88ddfbd5c9f6f65adec42b9b5a4cb1
  forest_auth_secret: dwAvXfF6tzsDd7MHVZtI1w
  secret_key_base: 8e28d5534d61090d34176d4a16cc5fedf9f32672e2ff8fcc8b61a47032ab3095260717275b35790ec31494fcba76b9997a96c6d2c59f38f4aa10e905fe07b43b

test:
  secret_key_base: 1875a768e5353708d9650da454a25fd1530e525366523583b8f5c983ade9f5284f81f9cfce14c46b26b0fce66935612cd6f8eb4aaa267fdaffa559d46a2cf827

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
